export const environment = {
  production: true,
  live_url: 'https://fcmdev.thestorywallcafe.com',
  //live_url:'https://fcmtest.thestorywallcafe.com',
  //live_url:'https://admin.firstclassmentor.com',
  lead_list:'/api/lead-list/',
  lead_status:'/api/lead-list-status/',
  lead_subStatus:'/api/lead-list-substatus/',
  lead_season:'/api/season/',
  lead_priority:'/api/priority/',
  lead_campaign:'/api/campaign-lead-list/',
  lead_course:'/api/course-leadlist/',
  lead_upload:'/api/upload-lead-data/',
  lead_refer:'/api/refer-lead-counsellor/',
  lead_note:'/api/note/',
  _user:'/api/user/',
  lead_email:'/api/send-emails/',
  raw_data:'/api/upload-lead-data/',
  lead_ids:`/api/get-lead-ids/`,
  whatsapp_template:`/api/template/`,
  lead_follow_up:`/api/add-follow-up/`,
  export_leads:`/api/export-leads/`,
  leadPayment:`/api/send-payment-link/`,
  paymentDetails:`/api/payment-details/`,
  rec_follow_up:`/api/rec-follow-up/`,
  tls_counsellor:`/api/counsellor-status-type/`,
  call_logs:`api/call-logs/`,
  counsellor_status:`/api/counsellor-status/`,
  call_log_status:`/api/call-logs-status/`,
  studying_stream:`/api/studying-stream/`,
  leadStage:`/api/lead-stage/`,
};
