export const environment = {
  production: true,
  
  
  //live_url:'https://admin.firstclassmentor.com',

  //Dev-server
  // live_url: 'https://fcmdev.thestorywallcafe.com',
  // lead_list:'https://fcmdev.thestorywallcafe.com/api/lead-list/',
  // lead_status:'https://fcmdev.thestorywallcafe.com/api/lead-list-status/',
  // lead_subStatus:'https://fcmdev.thestorywallcafe.com/api/lead-list-substatus/',
  // lead_season:'https://fcmdev.thestorywallcafe.com/api/season/',
  // lead_priority:'https://fcmdev.thestorywallcafe.com/api/priority/',
  // lead_campaign:'https://fcmdev.thestorywallcafe.com/api/campaign-lead-list/',
  // lead_course:'https://fcmdev.thestorywallcafe.com/api/course-leadlist/',
  // lead_upload:'https://fcmdev.thestorywallcafe.com/api/upload-lead-data/',
  // lead_refer:'https://fcmdev.thestorywallcafe.com/api/refer-lead-counsellor/',
  // lead_note:'https://fcmdev.thestorywallcafe.com/api/note/',
  // _user:'https://fcmdev.thestorywallcafe.com/api/user/',
  // lead_email:'https://fcmdev.thestorywallcafe.com/api/send-emails/',
  // raw_data:'https://fcmdev.thestorywallcafe.com/api/upload-lead-data/',
  // lead_ids:`https://fcmdev.thestorywallcafe.com/api/get-lead-ids/`,
  // whatsapp_template:`https://fcmdev.thestorywallcafe.com/api/template/`,
  // lead_follow_up:`https://fcmdev.thestorywallcafe.com/api/add-follow-up/`,
  // export_leads:`https://fcmdev.thestorywallcafe.com/api/export-leads/`,
  // leadPayment:`https://fcmdev.thestorywallcafe.com/api/send-payment-link/`,
  // paymentDetails:`https://fcmdev.thestorywallcafe.com/api/payment-details/`,
  // rec_follow_up:`https://fcmdev.thestorywallcafe.com/api/rec-follow-up/`,
  // tls_counsellor:`https://fcmdev.thestorywallcafe.com/api/counsellor-status-type/`,
  // call_logs:`https://fcmdev.thestorywallcafe.com/api/call-logs/`,
  // counsellor_status:`https://fcmdev.thestorywallcafe.com/api/counsellor-status/`,
  // call_log_status:`https://fcmdev.thestorywallcafe.com/api/call-logs-status/`,
  // studying_stream:`https://fcmdev.thestorywallcafe.com/api/studying-stream/`,
  // leadStage:`https://fcmdev.thestorywallcafe.com/api/lead-stage/`,
  // device_token:`https://fcmdev.thestorywallcafe.com/api/device-token/`

  //Testing Server
  live_url:'https://fcmtest.thestorywallcafe.com',
  lead_list:'https://fcmtest.thestorywallcafe.com/api/lead-list/',
  lead_status:'https://fcmtest.thestorywallcafe.com/api/lead-list-status/',
  lead_subStatus:'https://fcmtest.thestorywallcafe.com/api/lead-list-substatus/',
  lead_season:'https://fcmtest.thestorywallcafe.com/api/season/',
  lead_priority:'https://fcmtest.thestorywallcafe.com/api/priority/',
  lead_campaign:'https://fcmtest.thestorywallcafe.com/api/campaign-lead-list/',
  lead_course:'https://fcmtest.thestorywallcafe.com/api/course-leadlist/',
  lead_upload:'https://fcmtest.thestorywallcafe.com/api/upload-lead-data/',
  lead_refer:'https://fcmtest.thestorywallcafe.com/api/refer-lead-counsellor/',
  lead_note:'https://fcmtest.thestorywallcafe.com/api/note/',
  _user:'https://fcmtest.thestorywallcafe.com/api/user/',
  lead_email:'https://fcmtest.thestorywallcafe.com/api/send-emails/',
  raw_data:'https://fcmtest.thestorywallcafe.com/api/upload-lead-data/',
  lead_ids:`https://fcmtest.thestorywallcafe.com/api/get-lead-ids/`,
  whatsapp_template:`https://fcmtest.thestorywallcafe.com/api/template/`,
  lead_follow_up:`https://fcmtest.thestorywallcafe.com/api/add-follow-up/`,
  export_leads:`https://fcmtest.thestorywallcafe.com/api/export-leads/`,
  leadPayment:`https://fcmtest.thestorywallcafe.com/api/send-payment-link/`,
  paymentDetails:`https://fcmtest.thestorywallcafe.com/api/payment-details/`,
  rec_follow_up:`https://fcmtest.thestorywallcafe.com/api/rec-follow-up/`,
  tls_counsellor:`https://fcmtest.thestorywallcafe.com/api/counsellor-status-type/`,
  call_logs:`https://fcmtest.thestorywallcafe.com/api/call-logs/`,
  counsellor_status:`https://fcmtest.thestorywallcafe.com/api/counsellor-status/`,
  call_log_status:`https://fcmtest.thestorywallcafe.com/api/call-logs-status/`,
  studying_stream:`https://fcmtest.thestorywallcafe.com/api/studying-stream/`,
  leadStage:`https://fcmtest.thestorywallcafe.com/api/lead-stage/`,
  device_token:`https://fcmtest.thestorywallcafe.com/api/device-token/`

  //docker server
  // live_url:'http://127.0.0.1:8005',
  // lead_list:'http://127.0.0.1:8005/api/lead-list/',
  // lead_status:'http://127.0.0.1:8005/api/lead-list-status/',
  // lead_subStatus:'http://127.0.0.1:8005/api/lead-list-substatus/',
  // lead_season:'http://127.0.0.1:8005/api/season/',
  // lead_priority:'http://127.0.0.1:8005/api/priority/',
  // lead_campaign:'http://127.0.0.1:8005/api/campaign-lead-list/',
  // lead_course:'http://127.0.0.1:8005/api/course-leadlist/',
  // lead_upload:'http://127.0.0.1:8005/api/upload-lead-data/',
  // lead_refer:'http://127.0.0.1:8005/api/refer-lead-counsellor/',
  // lead_note:'http://127.0.0.1:8005/api/note/',
  // _user:'http://127.0.0.1:8005/api/user/',
  // lead_email:'http://127.0.0.1:8005/api/send-emails/',
  // raw_data:'http://127.0.0.1:8005/api/upload-lead-data/',
  // lead_ids:`http://127.0.0.1:8005/api/get-lead-ids/`,
  // whatsapp_template:`http://127.0.0.1:8005/api/template/`,
  // lead_follow_up:`http://127.0.0.1:8005/api/add-follow-up/`,
  // export_leads:`http://127.0.0.1:8005/api/export-leads/`,
  // leadPayment:`http://127.0.0.1:8005/api/send-payment-link/`,
  // paymentDetails:`http://127.0.0.1:8005/api/payment-details/`,
  // rec_follow_up:`http://127.0.0.1:8005/api/rec-follow-up/`,
  // tls_counsellor:`http://127.0.0.1:8005/api/counsellor-status-type/`,
  // call_logs:`http://127.0.0.1:8005/api/call-logs/`,
  // counsellor_status:`http://127.0.0.1:8005/api/counsellor-status/`,
  // call_log_status:`http://127.0.0.1:8005/api/call-logs-status/`,
  // studying_stream:`http://127.0.0.1:8005/api/studying-stream/`,
  // leadStage:`http://127.0.0.1:8005/api/lead-stage/`,
  // device_token:`http://127.0.0.1:8005/api/device-token/`

  //Admin
//  live_url: 'https://admin.firstclassmentor.com',
//   lead_list:'https://admin.firstclassmentor.com/api/lead-list/',
//   lead_status:'https://admin.firstclassmentor.com/api/lead-list-status/',
//   lead_subStatus:'https://admin.firstclassmentor.com/api/lead-list-substatus/',
//   lead_season:'https://admin.firstclassmentor.com/api/season/',
//   lead_priority:'https://admin.firstclassmentor.com/api/priority/',
//   lead_campaign:'https://admin.firstclassmentor.com/api/campaign-lead-list/',
//   lead_course:'https://admin.firstclassmentor.com/api/course-leadlist/',
//   lead_upload:'https://admin.firstclassmentor.com/api/upload-lead-data/',
//   lead_refer:'https://admin.firstclassmentor.com/api/refer-lead-counsellor/',
//   lead_note:'https://admin.firstclassmentor.com/api/note/',
//   _user:'https://admin.firstclassmentor.com/api/user/',
//   lead_email:'https://admin.firstclassmentor.com/api/send-emails/',
//   raw_data:'https://admin.firstclassmentor.com/api/upload-lead-data/',
//   lead_ids:`https://admin.firstclassmentor.com/api/get-lead-ids/`,
//   whatsapp_template:`https://admin.firstclassmentor.com/api/template/`,
//   lead_follow_up:`https://admin.firstclassmentor.com/api/add-follow-up/`,
//   export_leads:`https://admin.firstclassmentor.com/api/export-leads/`,
//   leadPayment:`https://admin.firstclassmentor.com/api/send-payment-link/`,
//   paymentDetails:`https://admin.firstclassmentor.com/api/payment-details/`,
//   rec_follow_up:`https://admin.firstclassmentor.com/api/rec-follow-up/`,
//   tls_counsellor:`https://admin.firstclassmentor.com/api/counsellor-status-type/`,
//   call_logs:`https://admin.firstclassmentor.com/api/call-logs/`,
//   counsellor_status:`https://admin.firstclassmentor.com/api/counsellor-status/`,
//   call_log_status:`https://admin.firstclassmentor.com/api/call-logs-status/`,
//   studying_stream:`https://admin.firstclassmentor.com/api/studying-stream/`,
//   leadStage:`https://admin.firstclassmentor.com/api/lead-stage/`,
//   device_token:`https://admin.firstclassmentor.com/api/device-token/`
};
